/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedLogo: typeof import('./src/components/AnimatedLogo.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    QuatiMascot: typeof import('./src/components/QuatiMascot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
